# Generated by Django 4.1.7 on 2023-04-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
